SELECT fh.FLAVOR 
FROM FIRST_HALF fh
LEFT JOIN 
    (SELECT SUM(TOTAL_ORDER) AS TOTAL_ORDER,FLAVOR
    FROM JULY
    GROUP BY FLAVOR) j
ON fh.FLAVOR = j.FLAVOR
ORDER BY fh.TOTAL_ORDER+j.TOTAL_ORDER DESC
LIMIT 3